name: Deploy Docs
on:
  push:
    branches:
      - '1.0'
    paths:
      - 'packages/fes-doc/**/**'
      - 'package.json'
jobs:
  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   steps:
    # - name: Checkout
    #   uses: actions/checkout@master
    # - name: Build and Deploy
    #   uses: JamesIves/github-pages-deploy-action@master
    #   env:
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     BRANCH: gh-pages
    #     FOLDER: packages/fes-doc/docs/.vuepress/dist
    #     BUILD_SCRIPT: cd packages/fes-doc && npm install && npm run build && cd ../../
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    
    - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      run: cd packages/fes-doc & yarn && yarn build

    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        # æœ¬åœ°.sshæ–‡ä»¶ä¸‹çš„ç§é’¥id_rsaï¼Œå­˜åœ¨secretsçš„TOKENä¸­
        SSH_PRIVATE_KEY: ${{ secrets.HARRYWAN_PRIVATE_KEY }} 
        # æºç›®å½•ï¼Œç›¸å¯¹äº$GITHUB_WORKSPACEæ ¹ç›®å½•çš„è·¯å¾„
        SOURCE: packages/fes-doc/docs/.vuepress/dist
        # æœåŠ¡å™¨åŸŸå
        REMOTE_HOST: ${{ secrets.TX_IP }}
        # è…¾è®¯äº‘é»˜è®¤ç”¨æˆ·åä¸ºroot
        REMOTE_USER: root 
        # ç›®æ ‡ç›®å½•
        TARGET: /data/web-packages/p/fesjs/1.0
