name: Deploy Docs
on:
    push:
        branches:
            - master
        paths:
            - 'docs/**/**'
            - 'package.json'
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: 8.1.0

            - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
              run: pnpm i && pnpm docs:build

            - name: Deploy
              uses: easingthemes/ssh-deploy@main
              env:
                  # æœ¬åœ°.sshæ–‡ä»¶ä¸‹çš„ç§é’¥id_rsaï¼Œå­˜åœ¨secretsçš„TOKENä¸­
                  SSH_PRIVATE_KEY: ${{ secrets.HARRYWAN_PRIVATE_KEY }}
                  # æºç›®å½•ï¼Œç›¸å¯¹äº$GITHUB_WORKSPACEæ ¹ç›®å½•çš„è·¯å¾„
                  SOURCE: docs/.vitepress/dist/
                  # æœåŠ¡å™¨åŸŸå
                  REMOTE_HOST: ${{ secrets.TX_IP }}
                  # è…¾è®¯äº‘é»˜è®¤ç”¨æˆ·åä¸ºroot
                  REMOTE_USER: root
                  # ç›®æ ‡ç›®å½•
                  TARGET: /data/web-packages/p/fesjs

    build-and-deploy-pages:
        concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ğŸ›ï¸
              uses: actions/checkout@v3

            - name: PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: 8.1.0

            - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
              run: |
                  pnpm i
                  pnpm docs:build-pages
            - name: Deploy ğŸš€
              uses: JamesIves/github-pages-deploy-action@v4.3.3
              with:
                  branch: gh-pages # The branch the action should deploy to.
                  folder: docs/.vitepress/dist
                  token: ${{ secrets.ACCESS_TOKEN }}
